## Put comments here that give an overall description of what your
## functions do

## Write a short comment describing this function

makeCacheMatrix <- function(x = matrix()) {
  m <- NULL
  set <- function(y) { 
    x <<- y
    m <<- NULL
  }
  get <- function() x
  setmat <- function(solve) m <<- solve
  getmat <- function() m
  list(set = set, get = get,setmat = setmat,getmat = getmat)
}


## cacheSolve function takes the matrix generated by makeCacheMatrix as an argument
## it                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 


cacheSolve <- function(x, ...) {
  m <- x$getmat()
  if(!is.null(m)) {
    message("getting cached data")
    return(m)
  }
  data <- x$mat()
  m <- mean(data, ...)
  x$setmat(m)
  m ## Return a matrix that is the inverse of 'x'
}
