## this function takes an argument which is of the class matrix (defined x which is an empty matrix)
## m is an object which will be used to store inverted matrix
## set is a function in which the value of y (a new vector) is assigned to x within the function and reset the value of m to NULL 
## get functions returns a matrix x
## setmat function returns the inverse of matrix assigned to m
## getmat function returns the inverse of the matrix
## the functions are then assigned as elements in a list which makes it easier to subset the elements using $ operator
 

makeCacheMatrix <- function(x = matrix()) {
  m <- NULL
  set <- function(y) { 
    x <<- y
    m <<- NULL
  }
  get <- function() x
  setmat <- function(solve) m <<- solve
  getmat <- function() m
  list(set = set, get = get,setmat = setmat,getmat = getmat)
}


## cacheSolve function takes the matrix generated by makeCacheMatrix as an argument
## it then checks if getmat() which contains the solved matrix is empty or not
## If it is not empty, it returns the cached inverted matrix otherwise it calculates and returns the cache
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             


cacheSolve <- function(x, ...) {
  m <- x$getmat()
  if(!is.null(m)) {
    message("getting cached data")
    return(m)
  }
  data <- x$mat()
  m <- mean(data, ...)
  x$setmat(m)
  m ## Return a matrix that is the inverse of 'x'
}
